baseURL = "https://evgenn3d.github.io/portfolio/"
#baseURL = "http://localhost:1313/"
title = 'Portfolio'
theme = "theme1"
publishDir = "docs"
defaultContentLanguage = "ru"
languageCode = "ru-RU"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "подробнее/"
  url = "about/"

  [[params.navlinks]]
  name = "статьи/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "галерея/"
  url = "gallery/"